writeLines('PATH="${RTOOLS40_HOME}\\usr\\bin;${PATH}"', con = "~/.Renviron")
if (!require(devtools)) install.packages("devtools")
remove.packages("devtools")
myPaths <- .libPaths()
myPaths <- c(myPaths[2], myPaths[1])
.libPaths(myPaths)
.libPaths()
myPaths <- .libPaths()
myPaths <- c(myPaths, "C:/CustomR")
.libPaths(myPaths)
devtools::install_github("EDUCE-UBC/educer")
1
library("dplyr")
library("learnr")
library("readr")
library("tidyverse")
install.packages("tidyverse")
